###########
# site.title

title:    'Kurtis Thrasher'
subtitle: 'Computer Science student @ 
Hull University with a keen interest in web technologies.'


nav:
- { title: 'Welcome',              href: '/' }
- { title: 'About',                href: 'https://github.com/kthrasher1' }


#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md

