###########
# site.title

title:    'Kurtis Thrasher'
subtitle: 'Computer Science student @ 
Hull University with a keen interest in web technologies.'


nav:
- { title: 'Home',                 href: '/' }
- { title: 'About',                href: 'https://github.com/kthrasher1'}
- { title: 'Porfolio',             href: 'http://kurtisthrasher.co.uk' }


#########################
# more settings

markdown: kramdown

url: http://blog.kurtisthrasher.co.uk

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md

